### ISSUE TITLE
Proposal: throttle QPS globally to mitigate back pressure effect

### ISSUE THREAD

**Issue by ezsilmar** [bojand/ghz#111]
Hello,

Thanks again @bojand for the tool and your great support !

The proposal I have is quite small and easy to implement. More important is that it opens door for other improvements. I'm not sure that ghz will go that way but I think it's at least worth to discuss.

**Proposal**

Basically, let's have a single "ticker" for QPS which is shared by all the workers. The meaning of `qps` parameter should be changed accordingly. 

**Motivation**

The one thing we need to ensure during the loadtest is that QPS produced by the tool is reliable. For instance, if we set `qps = 100`, each second we want 100 requests to be started, no matter what latency our service has. However now, if normal service latency is 2 seconds, you need at least `concurrency = 200` to achieve this behavior (because threads wait for the answer). With this concurrency, you should set `qps = 0.5` to have 100 qps as a result. It not only looks strange but doesn't guarantee anything: if server degrades and starts to answer slowly, workers will "skip" their tick and the load will lessen. Setting `timeout=2s` helps a bit but is not always applicable, f.e. if you want to measure the latency at 100 qps with the test.

With the proposed change, it would be possible to have more workers than qps. With high enough `concurrency`, there will always be a worker to process the tick and this back-pressure effect will not happen.

**Opportunities**

With the change, we can reliably answer if the service can handle `qps=N` or not. The next step could be to support changing qps during the test to find a breaking point. This can be achieved with line schedule (go from 1 qps to 1k qps in 5 min). 

The chart looks like that:
![image](https://user-images.githubusercontent.com/5860161/61125037-eed66600-a4a8-11e9-908a-83f9177c4e6c.png)

There's a point for every second of the test. We take all requests which started at the same second and compute several metrics for the "bucket": ok and error qps, and percentiles. Timeout is set to 500ms, so when latency rises, we have client-side timeouts which are treated as qpsError. The breaking point is around 700 qps.

Similar behavior is implemented in other load testing tools, for example [Yandex.Tank](https://github.com/yandex/yandex-tank) which is very convenient for testing HTTP services.

**Further**

Finding maximum stable qps with the given SLA on latency could be automated. Tool could analyze bucket metrics in real-time to judge if it needs to increase or lower the qps, allocating workers accordingly. As test output, we can have a single number - maximum reliable qps the server can handle.

As far as I know, there's no load tool which can do this now :) However I believe that's possible and will be very useful in the field.

**MVP**

Part with linear load and a chart in html output is implemented in criteo ghz fork, please try it out: https://github.com/criteo-forks/ghz/tree/v0.37.0-criteo. 
It's of course not a production-ready design but shows that at least this is possible and works.

**Comment by bojand** [comment]
Hello, thanks for putting this issue together. I finally got around to taking a look into it and thinking about some more, and was wondering if I could get some clarification. 

My understanding is that at a high level there are three main points in this issue, that may be easier to think about as separate:
- Allow a QPS parameter to basically mean "queries attempted per second". Basically this should be how many requests are attempted at a call. I agree the current QPS which just spaces out requests with a time duration is not intuitive and useful really.
- In general allow for a step up behaviour, where we want to grow (new) QPS up to some limit at some rate or interval. The results should be recorded and reported in a useful manner like you have it in a screenshot where we can tell at what QPS point errors start occurring. Optionally we would have a starting QPS, that is min QPS where we start and max QPS.
- Build in automatic mechanism where the tool finds a maximum reliable qps "sweet spot" that the service can handle. For sake of discussion on this issue let's ignore this last point and feature for now.

I looked at the code and I understand it also contains some of the behaviour for the step / growth functionality. I find some of the code a little bit confusing because it compares and does operations (differences) with both `qps` and `qps2`, so I am not sure I understand the connection between the two, as is in the code. Is it treating `qps` as the min / starting QPS?

Something else that's slightly unclear about what's asked is with regard to the new "QPS" param and its connection with the concurrency param. In the current implementation of ghz, it spaces out requests in _each worker_ (specified by `concurrency` option). What seems to be desired is qps that represents "queries attempted at service that the service sees", so as you suggest qps is somewhat global regardless of concurrency. If you can elaborate on this and what the desired functionality is it would be helpful, as it's not super clear to me based on description above and code changes in the branch you linked. 

What would help is perhaps some example CLI options and description of ideal behaviour and functionality, forgetting current options if necessary. 

Looking forward to some more information. Thanks!

**Comment by ezsilmar** [comment]
Hello @bojand, sorry for the delay :)

Yes, your high-level understanding is correct. The proposal could be separated in three different issues and I agree that the third one could be ignored for now.

So `qps` means "queries attempted from the client-side, per second". It doesn't say how many queries each worker should fire (so no connection with `concurrency`), just the total number of requests for the time period. `Concurrency` doesn't really matter in that case, as far as it is high enough. It only limits the number of requests which could be "in-flight" simultaneously.

For example, imagine `qps = 100` and the server which always responds in `20 ms`. In this case, the single worker is only able to make 50 queries per second (`1 s / 20 ms`), so `concurrency` should be at least 2 to reach desired load. It's of course ok to set `concurrency` to a higher value than 2. In that case, workers would sometimes be throttled and would wait before starting new request, as in the current implementation.

The difference is that "free" workers (which are throttled) could now help the "stuck" ones (which wait for the response longer than expected). In the above example, imagine that one request accidentally took `100 ms` to complete. It means that one worker "missed" to start 4 requests because it waited for the answer. In the current implementation, these 4 requests would not be started resulting in 96 qps totally. But with the new impl, if `concurrency` is set to at least 3, there would be a "free" worker which back-ups the "stuck" one.

About the confusion between qps/qps2 in the linked branch: `qps` is intended to be the starting load and `qps2` is the load when the test ends. The load will gradually change from `qps` to `qps2` throughout the test, so it could be both increasing (`qps < qps2`) and decreasing (`qps > qps2`). It's definitely more complicated than it should be, as "decreasing" scenario is only reasonable with more complex schedule, f.e. when one wants to emulate "spiky" load.

Hope my explanation clears up things a bit :)

**Comment by tp** [comment]
Just as a note, I was also looking for a feature to control the overall outgoing QPS, which is what the first part seems to allude to.

I am not sure about the connection to the workers (`concurrency`) though. Is it really desirable / not an issue to set them super high? (E.g. I want a QPS of 1000, maximum timeout is 2s, so I would need 2000 workers just to be safe no query is skipped.)

**Comment by craigh1015** [comment]
QPS as a global rather than per worker throttle would make the feature far more useful.

The second issue reminds me of one of the most useful features that I use in my http testing with [taurus/blazemeter](https://gettaurus.org/docs/ExecutionSettings/#Load-Profile)

In that case it is providing stepping of concurrency rather than throughput.

From a usage perspective it would helpful to be able to specify the following:

- lower bound of the parameter (qps-start)
- upper bound of the parameter (qps-end)
- number of step changes in the parameter (qps-steps)
- number of seconds over which the paremeter is changing (qps-ramp)

As an example I may want to test an api at sustained rates of 100, 200, 300, 400 qps spending 60 seconds at each level before increasing

I would define --qps-start=100 --qps-end=400 --qps-steps=4 --qps-ramp=4m

This would be start at 100, increase to 400 in 4 steps over 4 mins

**Comment by bojand** [comment]
Hello, I think most of what's requested here (minus automatically detecting when errors start occurring) should be available in [0.70.0](https://github.com/bojand/ghz/releases/tag/v0.70.0).
