### ISSUE TITLE
Hello, what is the calculation formula for Latency distribution and Response time?

### ISSUE THREAD

**Issue by helloqhq** [bojand/ghz#150]
Hello, what is the calculation formula for Latency distribution and Response time?

**Comment by bojand** [comment]
Hello, I am not really sure I understand the question but the latency distribution is simply calculated using percentiles. Please refer to the [code here](https://github.com/bojand/ghz/blob/master/runner/reporter.go#L233).

**Comment by BesSlaaneshi** [comment]
https://en.wikipedia.org/wiki/Normal_distribution

  "total": 250,
  "concurrency": 5,
  "qps": 5,
  "connections": 5,

for me - this "latency distribution" looks really strange
![изображение](https://user-images.githubusercontent.com/40031332/72046231-0318e580-32c9-11ea-8b5a-d0f69495acf3.png)

And this report is even more strange
  "total": 5,
  "concurrency": 5,
  "qps": 5,
  "connections": 5,

![изображение](https://user-images.githubusercontent.com/40031332/72046414-728ed500-32c9-11ea-88da-5ec28d951379.png)

**Comment by craigh1015** [comment]
What is it about your data that you feel is strange?

In my experience request response times are rarely a Normal distribution. You will get a cluster around the most frequent values and then typically a long tail of outliers. The outliers are often caused by intermittent interruptions (quite often garbage collection). This could easily account for your second distribution. I would also recommend using much higher number of requests to ensure you are getting representative results.
