### ISSUE TITLE
Support for binary metadata fields

### ISSUE THREAD

**Issue by mklamra** [bojand/ghz#167]
There is currently no support in ghz to send binary metadata fields to a gRPC server. All fields are sent as strings. This makes it hard to use ghz in some use cases.

The convention in gRPC seems to be to name binary fields with the suffix "-bin". A way of supporting binary metadata fields in ghz would be to assume that all fields suffixed with "-bin" are base64 encoded and then decode them to binary format before sending them to the server. For example, if you run `./ghz -m ‘{“foo-bin":"Zm9vYmFy"}'`, the value sent to the server for the "foo-bin" field would be the base64 decoded value for "Zm9vYmFy" instead of the string "Zm9vYmFy".

**Comment by hovinen** [comment]
It seems that it is also not possible to specify binary metadata programmatically. There unfortunately appears to be no way to use ghz to send RPCs which require binary metadata.

Is there any timeline when this will be fixed?

Right now we are considering using ghz for load tests, since it is otherwise an extremely good match for our needs, but this is an absolute blocker for us. If it can't be fixed any time soon, we'll have to use a different tool.

Alternatively, I'm happy to produce a PR if you can give me some pointers on how to add this. I have dug around the code but it's not clear to me how one would proceed.

**Comment by bojand** [comment]
Hello, gRPC metadata is language dependent. Can you please elaborate on your use case and the type of solution you would like to see?

`ghz` is written in Go so metadata is just a map [from string to a list of strings](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md). The core of the CLI can be used programmatically as a [Go package](https://pkg.go.dev/github.com/bojand/ghz@v0.93.0), and there are a handful of options for specifying metadata, including [WithMetadata](https://pkg.go.dev/github.com/bojand/ghz@v0.93.0/runner#WithMetadata), and [WithMetadataProvider](https://pkg.go.dev/github.com/bojand/ghz@v0.93.0/runner#WithMetadataProvider). If you can use base64 encoded string representation of binary data, then these should suffice. Please refer to tests inside the repo for example usage. Hope this helps.
