### ISSUE TITLE
Html report charts are not visible 

### ISSUE THREAD

**Issue by Jaydev13** [bojand/ghz#190]
**Describe the bug**
The reports generated does not show the charts since the css being used could not be fetched.
This is because the server where the reports are generated has policy which adds "content-security-policy" as "style-src 'self'" for response headers in the report.html file.

The css files are present in the cdn repo.
britecharts.min.css - https://cdn.jsdelivr.net/npm/britecharts/dist/css/britecharts.min.css
bulma.min.css - https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css

I am running the ghz tool using apache-jenkins. The reports are shown on the jenkins html page.

**To Reproduce**
1. Create a web server and place the generated html file.
2. Configure the web server to add request header "content-security-policy" as "style-src 'self'".
3. View the html by hitting the web-server.

**Expected behavior**
Please add both the css files in the repo and generate the css as well while generating the html report so that it does not have to fetch it from cdn.

**Environment**
 - ubuntu 18.04
 - ghz: 0.54.0

**Comment by bojand** [comment]
I believe this is issue due to jenkins web server that serves the HTML report hsd the CSP policy configured such that other javascript files not served from the same server are prohibited from being loaded. Quickly searching, this [jenkins documentation](https://support.cloudbees.com/hc/en-us/articles/360034545912-What-is-Content-Security-Policy-and-how-does-it-impact-Jenkins-#context) may help.
