### ISSUE TITLE
send binary data in stringified JSON

### ISSUE THREAD

**Issue by justinlarose** [bojand/ghz#44]
We need to send binary data in our stringified JSON request metadata. 

For example:
```
./ghz -proto grpc-service.proto -call service.Put -d {"primarykey": "6C-getList:8bb1e1f6f-loadtest1k","value": "½ƒ]Ä0/™)ûÆ´Ÿù.å³PË¼ñÁ»9¦W¡w¦Ë–s‹Ã]±ÔÖ‡,l`×Ñtz(´7,ÆŸ","ttl": 300} -c 1 -z 60s grpc.endpoint.service.com:8080
```
We tried to send using `-D` flag with a path to a JSON file with the binary data as well. But I think it is either the shell or ghz can not interpret the binary data therefore fails. Are there any suggestion on how we can send binary data using ghz?

We get errors like `invalid character 'Ä' looking for beginning of value`.

**Comment by bojand** [comment]
Hello,

Are we talking about **metadata** or actual **message data**?

For actual message data you should be able to use the `-B` option. Simply [serialize the whole](https://developers.google.com/protocol-buffers/docs/gotutorial#writing-a-message) message to a file first. Then use the file with `-B ./my_message.bin` for example. This is usually more practical when having to deal with some of the message having binary data.

I am assuming the type of `value` field is `bytes`? You can try and input that binary data like you have it above, but probably would have to [use base64 string](https://developers.google.com/protocol-buffers/docs/proto3#json) as the value for that field and then the unmarshalling within `ghz` should work I think. I haven't really tried this type of thing yet. Will test it soon when I get some time.

As for [metadata](https://grpc.io/docs/guides/concepts.html#metadata), it's simply k/v pairs, usually of string-string data. We only support JSON metadata right now (read from CLI or file). We currently do not support inputting metadata with plain binary serialization. I am not even sure how that would look or work, since proto buffers doesn't really have anything to do with gRPC metadata. My suggestion is avoid having binary values within metadata. If you have to, the only thing I can think of right now in order to make it work with `ghz` is to use base64 encoded value for metadata as well, but then your server would have to be aware of it and know if it's getting base64 metadata value and handle it appropriately.

Good luck!

**Comment by justinlarose** [comment]
thanks for the information @bojand. I apologize for the confusion in my post, I was verifying to the *message data* not *metadata*. I made the correction to the flag. We will try base64 encoding the data. Will let you know the results.

**Comment by justinlarose** [comment]
@bojand base64 encoding the data worked! thank you!
