### ISSUE TITLE
ServerStreaming call metadata specification

### ISSUE THREAD

**Issue by david-garay** [bojand/ghz#48]
Hi there,
While trying to call my server using ghz, I see on the wire that the initial setup does not have any metadata, and eventually tcp session gets reset (it works fine from ballerina client, but I would like to use the nice load testing and reporting facilities :)

Command in question (tried many -m variations without luck):

 ghz -name "Testing" -c 1 -n 100 -insecure -proto ../server/target/grpc/HelloWorld.proto -d '{"req":"Sam"}' -m '{"IsServerStreaming":"true"}' -call service.HelloWorld/lotsOfReplies localhost:9095

.proto in question:
syntax = "proto3";
package service;
import "google/protobuf/wrappers.proto";
service HelloWorld {
                rpc lotsOfReplies(google.protobuf.StringValue) returns (stream google.protobuf.StringValue);
}

Your thoughts on this would be highly appreciated!

David

**Comment by bojand** [comment]
Hello, looked into this... Since you are using wrapped types from `google/protobuf/wrappers.proto` you should use `-i` to specify the include path (there is `/inlcude` directory wherever you have `protoc` installed that should have all the common types). Additionally, [`StringValue`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#stringvalue) has just one string field `value`, which should be set. So the correct data for this should be `-d '{"value":"Sam"}'`. Regardless of all of this... even if I make the call correctly (as far as I can tell) the call fails in our request code when we try to [unmarshal the data](https://godoc.org/github.com/golang/protobuf/jsonpb#UnmarshalString) with `json: cannot unmarshal object into Go value of type string`. Unfortunately currently we do not do a good job of reporting these type of errors that happen within our request code in the middle of the test; we just swallow them up. I'll work on improving this. I'll also have to dig deeper why jsonpb does not seem to like `StringValue` or if we are doing something wrong in our code. There is a workaround though, simply provide your own request and reply messages. Example proto file:

```proto
syntax = "proto3";

package service;

// import "google/protobuf/wrappers.proto";

service HelloWorld {
    rpc LotsOfReplies(Req) returns (stream Res);
}

message Req {
    string value = 1;
}

message Res {
    string value = 1;
}
```

Here's a sample server in Node.js

```js
const path = require('path')
const grpc = require('grpc')
const protoLoader = require('@grpc/proto-loader')

const PROTO_PATH = path.join(__dirname, './helloworld.proto')

const packageDefinition = protoLoader.loadSync(PROTO_PATH)
const proto = grpc.loadPackageDefinition(packageDefinition).service

const HOSTPORT = '0.0.0.0:50051'

function lotsOfReplies(call) {
  console.log('server:lotsOfReplies')

  console.dir(call.request, { depth: 3, colors: true })
  console.dir(call.metadata, { depth: 3, colors: true })

  let count = 5
  let n = 0
  const timer = setInterval(() => {
    if (n < count) {
      call.write({ value: `Hello ${call.request.value} ${n}` })
      n++
    } else {
      clearInterval(timer)
      call.end()
    }
  }, 200)
}

function main() {
  var server = new grpc.Server()

  server.addService(proto.HelloWorld.service, { lotsOfReplies })

  server.bind(HOSTPORT, grpc.ServerCredentials.createInsecure())
  server.start()
}

main()
```

Then using sample call:

```sh
./ghz -insecure -proto helloworld.proto -call service.HelloWorld/LotsOfReplies -c 1 -n 100 -d '{"value":"Sam"}' -m '{"IsServerStreaming":"true"}' localhost:50051
```

The data and metadata comes through fine:

```
server:lotsOfReplies
{ value: 'Sam' }
Metadata {
  _internal_repr:
   { 'user-agent': [ 'grpc-go/1.11.1' ],
     isserverstreaming: [ 'true' ] } }
```

And I get results:

```
Summary:
  Count:	100
  Total:	122088.20 ms
  Slowest:	1231.35 ms
  Fastest:	1210.44 ms
  Average:	1220.37 ms
  Requests/sec:	0.82

Response time histogram:
  1210.445 [1]	|∎∎
  1212.536 [3]	|∎∎∎∎∎∎∎
  1214.627 [9]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1216.717 [16]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1218.808 [10]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1220.899 [17]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1222.990 [12]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1225.081 [13]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1227.172 [8]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1229.263 [8]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1231.354 [3]	|∎∎∎∎∎∎∎

Latency distribution:
  10% in 1214.41 ms
  25% in 1216.19 ms
  50% in 1220.67 ms
  75% in 1223.83 ms
  90% in 1227.66 ms
  95% in 1229.13 ms
  99% in 1231.35 ms
Status code distribution:
  [OK]	100 responses
```

**Comment by david-garay** [comment]
Absolutely fantastic. I used went ahead with implementing your workaround, and after fixing some errors on my end it works nicely. I am impressed and very happy with your helpful answer. Thank you!
