### ISSUE TITLE
How to run multiple gRPC requests in one test?

### ISSUE THREAD

**Issue by minddazed** [bojand/ghz#65]
This is a general question more than a bug, but I'm trying to figure out if the ghz framework is capable of running multiple gRPC requests in a flow type end to end test? This would imply some kind of request/response chaining which would make it more complex, but wondering if this would be possible. Thanks!

**Comment by BesSlaaneshi** [comment]
i make .bat file
like ```
@echo off
start rpc1.bat
start rpc2.bat
start prc3.bat
start rpc4.bat
start rpc5.bat
start rpc6.bat
start rpc7.bat
start rpc8.bat
start rpc9.bat
start rpc10.bat
```
and every rpc.bat looks like:
```
ghz -config .\rpc1.json
EXIT
```

**Comment by bojand** [comment]
Hello, thanks for the question. If it's to do separate measurements, that would be easy, and similar to what was suggested above, just run ghz tests in sequence. If something different is meant, for example, to have a mechanism to do concurrency and measure the responses, but a single measurement is a series of sequential gRPC calls...? Right now there is no real easy way to accomplish this. Something I have been thinking of potentially is expanding on the Go API of the package to allow for custom "call action" where basically that's measured instead of our calls. Then it would be easier to write a custom application to do the tests using custom calls. But on the other hand that would be getting away from a purposeful and focused package, to something that's more general, and perhaps it's not a direction that `ghz` should go into. It's hard to get the balance right. There are other tools that probably would accomplish such a task more sensibly, such as [hazana](https://github.com/emicklei/hazana) or perhaps [fperf](https://github.com/fperf/fperf). Note I have not used either of these packages so I can't speak to their functionality or usability, but just know of them. But it may be options to explore if you need more customized behaviour.

**Comment by minddazed** [comment]
Thanks for the quick feedback! I definitely understand your comment about finding the right balance and trying to keep focus on the tool! :) Will take a look at some of the frameworks you mentioned. Hazana looks interesting.
