### ISSUE TITLE
Using different data for parallel calls

### ISSUE THREAD

**Issue by Shukla-Ankur** [bojand/ghz#82]
### Command line arguments / config
./ghz -insecure -proto document.proto \
-call DocService.CreateDoc \
-n 2 \
-c 2 \
-D ../SummaryDocs.json \
0.0.0.0:3000

### Expected Behavior
2 independent calls should go to the server, with 2 messages picked from the SummaryDocs.json file

### Actual Behavior
2 calls sent, with same data

I want to be able to send custom data for every call, instead of same data being used for all 'n' calls. How can that be achieved?

- OS:  Mojave 10.14.3
- ghz version: 0.32.0

**Comment by bojand** [comment]
Hello,

This is not something we support. In case of Unary calls, if data is an array we just take the first element and repeatedly send that. 

Why would this behaviour be desireable at all? Can you describe the context in more detail please. What would the data look like to specify this type of behaviour? Seems weird as it could introduce data-induced performance variance to measurements. Normally we want the same data for an entire test run. For example to illustrate the idea, lets say we have a service that calculates fibonacci numbers:

```proto
syntax = "proto3";
package fibonacci;

service FibonacciService {
  rpc Fib (FibRequest) returns (FibResponse) {}
}

message FibRequest {
  int32 num = 1;
}

message FibResponse {
  int32 res = 1;
}
```

Lets say our data was:

```
[
{ "num": 5 },
{ "num": 50 }
]
```

And we sent `5` to all calls to one parallel request, and `50` to another. The call for computing `50` takes a lot longer than the call with `5`. But our summary would aggregate and average all of this out. 

Rather I would think we would do one whole run (with whatever concurrency) for `5` and another for `50` and that way we have identical measurements, where we actually change the data. That way we can work to optimize our service for different data (if only we could optimize Fibonacci!). But you can imagine if our service was not fibonaccy but something else where we take an array of data and we need to be able to scale with increased elements, or some other computation property.

In general we _could_ do something like this, or perhaps take an array of elements for Unary requests and cycle those, but it would complicate the code, and also introduce the problem of variance, which I do not think most users desire. But perhaps I am not understanding the context of your usage, so some more information would be helpful.

**Comment by minddazed** [comment]
I think the ask to use varied data is a practical one for load testing especially. For performance testing, using the same data set makes more sense. But for load it more makes sense to randomly generate different input values and see how different data sets perform in terms of a normalized distribution since that will be closer to real user behavior.

**Comment by bojand** [comment]
I understand how some feature like this can be useful. I'll try and think about how to do this elegantly and practically without making the tool and logic complex and error-prone.

**Comment by ezsilmar** [comment]
Hello!

I need similar behavior for my load tests and have some time to work on this issue.
Work in progress is here: https://github.com/bojand/ghz/compare/master...criteo-forks:varied-data

Things I'd like to implement:
1. Use all provided data for parallel **unary** calls, not stick to the first message
2. Ability to specify several messages in a binary data file

The second is important in my use case. My requests contain binary data and it's easier to serialize several messages to raw protobuf than json.

I think it's better not to support round-robin and streaming simultaneously for now. This will significantly complicate the code. Also this feature could be added in the future with new cli options without breaking the "flat" data format.

Some technical aspects I was thinking about:
1. CreatePayloads may always return an array of messages
2. Let Worker choose between using a single message and a streaming case
3. Use CallTemplateData.RequestNumber to round robin messages
4. Use length delimited format in binary data

@bojand what do you think?

**Comment by bojand** [comment]
Hello,

First, thank you for taking the initiative and starting the working on this. This was the next issue I was going to try and tackle for ghz so it's nice to see that there is progress already!

I have taken a look at your changes and most of this looks pretty sane to me and the approach I would have taken. Also I did not realize I had so many typos / spelling mistakes! 😄 

So just to summarize from a high level the implemented changes so far (so we can check that my review & understanding is correct 😄 ) :

- We can now take a single message or an array of JSON data. Regardless what we get the data is converted into an array of messages and we cycle through them to send them for Unary calls. In case that we are given just a single JSON message, we convert it to an array with just that single message and the cycling logic will ensures we always just send that single message for Unary calls. For Client Streaming / BiDi calls the array is the data.  I like this change and seems very reasonable, and it's likely the approach I would have taken.
- In case for binary data, we have similar changes where we return an array of messages. But there is a requirement to support multiple messages that are encoded in the binary format data. The main outstanding piece is to know or have a mechanism to determine whether we need to decode a single binary message or an array (your `todo` and commented out tests).

So with regards to the distinguishing between single binary message or an array of binary messages... One possible approach would be to:

1. perform a test and see if a single message can be unmarshaled using `createPayloadsFromBinSingleMessage`
2. if this fails (which I think it should in case of multiple messages?) try to decode multiple messages using `createPayloadsFromBinCountDelimited` which hopefully should pass and then we know we have an array

We should do this once either at startup of the run (probably more ideal) or on the first request, and save the outcome in a flag so that we know which one of the 2 binary data decoding functions to call subsequently. With this mechanism, we would not really need to change the `options` API at all perhaps (ie add `WithBinaryDataCountDelimited`) as I think `WithBinaryData` should be able to handle both scenarios. Similarly, therefore existing command line flags should be sufficient. What are your thoughts on this approach?

Thanks for the work!

**Comment by ezsilmar** [comment]
Thank you for the fast review! Yes, your understanding of changes is fully correct 😄 

About choosing between binary formats: I tackled this piece yesterday and actually tried exactly the approach you suggest. Unfortunately this doesn't work. My first test data with several messages was successfully parsed by both `createPayloadsFromBinSingleMessage` and `createPayloadsFromBinCountDelimited`. Maybe I was really lucky to catch this case in the first try but it means these cases exist and may confuse users.

I was thinking about introducing new optional parameter `dataFormat` with three well-known values: `bin-single`, `bin-delimited`, `templated-json`. Using this parameter we may interpret `data` and `dataPath` options correctly. All `binary` options could be left as-is and marked obsolete to preserve backward compatibility. 

This approach has several advantages:
1. Users can clearly define their data format without "guessing" library behavior
2. Data source is separated from data interpretation. For example we can easily enable binary input from stdin or add new data formats :)
3. This opens a way to further optimizations. F.e. if someone uses json but doesn't use templating ghz may parse the data once and then reuse messages.

The disadvantages are larger and more complicated PR as well as backward compatibility support costs like tests and obsolete methods. But for me it seems better to include the change in this PR without introducing kind of "works-almost-always" behavior.

I will continue working on the issue after the weekend and we can just see if the amount of changes turns out to be reasonable. Thank you again for detailed comments :)

**Comment by bojand** [comment]
Hello,

Hmm I am able to get the "detection" working with a simple quick test app, but first checking for multiple messages and then a single message. It did not work with a single message first as the multiple message buffer still gets decoded into some data, albeit it was not correct data. Here is the code using the [grpc-go example](https://github.com/grpc/grpc-go/tree/master/examples/helloworld/helloworld) protobuf:

```go
package main

import (
	"fmt"
	"io"
	"log"

	"github.com/bojand/ghz/protodesc"
	"github.com/bojand/pbbintest/helloworld"
	"github.com/golang/protobuf/proto"
	"github.com/jhump/protoreflect/desc"
	"github.com/jhump/protoreflect/dynamic"
)

func main() {

	mtdUnary, err := protodesc.GetMethodDescFromProto(
		"main.Greeter.SayHello",
		"./helloworld/helloworld.proto",
		nil)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("test single message")
	testSingleBin(mtdUnary)
	fmt.Println()

	fmt.Println("testMultiBin")
	testMultiBin(mtdUnary)
	fmt.Println()
}

func testSingleBin(mtd *desc.MethodDescriptor) {
	msg1 := &helloworld.HelloRequest{}
	msg1.Name = "bob"

	binData, err := proto.Marshal(msg1)

	inputs, err := createInputs(binData, mtd)

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	if len(inputs) == 0 {
		fmt.Println("no inputs created")
		return
	}

	fmt.Printf("%+v\n", inputs)
	fmt.Printf("len: %+v\n", len(inputs))
	fmt.Printf("%+v\n", inputs[0])
	fmt.Printf("%+v\n", inputs[0].GetFieldByName("name"))
}

func testMultiBin(mtd *desc.MethodDescriptor) {
	msg1 := &helloworld.HelloRequest{}
	msg1.Name = "bob"
	msg2 := &helloworld.HelloRequest{}
	msg2.Name = "alice"

	buf := proto.Buffer{}
	_ = buf.EncodeMessage(msg1)
	_ = buf.EncodeMessage(msg2)

	inputs, err := createInputs(buf.Bytes(), mtd)

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	if len(inputs) == 0 {
		fmt.Println("no inputs created")
		return
	}

	fmt.Printf("%+v\n", inputs)
	fmt.Printf("len: %+v\n", len(inputs))
	fmt.Printf("%+v\n", inputs[0])
	fmt.Printf("%+v\n", inputs[0].GetFieldByName("name"))
	fmt.Printf("%+v\n", inputs[1])
	fmt.Printf("%+v\n", inputs[1].GetFieldByName("name"))
}

func createPayloadsFromBinSingleMessage(binData []byte, mtd *desc.MethodDescriptor) ([]*dynamic.Message, error) {
	var inputs []*dynamic.Message
	md := mtd.GetInputType()

	// return empty array if no data
	if len(binData) == 0 {
		return inputs, nil
	}

	// try to unmarshal input as a single message
	singleMessage := dynamic.NewMessage(md)
	err := proto.Unmarshal(binData, singleMessage)
	if err != nil {
		return nil, fmt.Errorf("Error creating message from binary data: %v", err.Error())
	}
	inputs = make([]*dynamic.Message, 1)
	inputs[0] = singleMessage

	return inputs, nil
}

func createPayloadsFromBinCountDelimited(binData []byte, mtd *desc.MethodDescriptor) ([]*dynamic.Message, error) {
	var inputs []*dynamic.Message
	md := mtd.GetInputType()

	// return empty array if no data
	if len(binData) == 0 {
		return inputs, nil
	}

	// try to unmarshal input as several count-delimited messages
	buffer := proto.NewBuffer(binData)
	for {
		msg := dynamic.NewMessage(md)
		err := buffer.DecodeMessage(msg)

		if err == io.ErrUnexpectedEOF {
			break
		}

		if err != nil {
			return nil, fmt.Errorf("Error creating message from binary data: %v", err.Error())
		}

		inputs = append(inputs, msg)
	}

	return inputs, nil
}

func createInputs(binData []byte, mtd *desc.MethodDescriptor) ([]*dynamic.Message, error) {
	inputs, err := createPayloadsFromBinCountDelimited(binData, mtd)

	if err == nil && len(inputs) > 0 {
		return inputs, err
	}

	return createPayloadsFromBinSingleMessage(binData, mtd)
}
```

I understand there are trade-offs to both approaches, guessing, or explicitly user-specified. To me I would prefer "guessing" approach at first at least unless we find out the guessing is not reliable and the behaviour I am seeing above is a fluke. I'll look further into this, but it seems it may still be a viable option to explore... Thoughts?

**Comment by bojand** [comment]
I had some time to experiment with this some more using the `routeguide` proto and was able to get it working properly with similar setup as above for `Feature` messages, so it would seem this approach may be viable.

**Comment by ezsilmar** [comment]
Hello,

Indeed, "detection" works fine if we try to parse as count-delimited first. Haven't thought about reversing the order because it could be a breaking change. I.e. someone's test may now fail to parse bin data as a single message because the data has been successfully parsed to "wrong" multiple messages. However the approach doesn't fail on my data (I should test it more thoroughly though) so it seems to be a nice trade-off for now.

I'll do some cleanup and submit a PR.

**Comment by DevikaNuclei** [comment]
how does the "-D" option work with these merged changes now?

**Comment by ezsilmar** [comment]
@DevikaNuclei the only difference is when for `-D` you pass a file with json array inside and `--call` specifies an unary call. 

In this case previous version would take the first object from the array and use it as a single message throughout the test, the rest of array ignored. New version however will use all provided messages. 

For example the data is `[{"name":"Bob"}, {"name":"Alice"}]` and `-n` is 4. The old version will send "Bob" message 4 times, the new version will send "Bob", "Alice", "Bob", "Alice".

**Comment by DevikaNuclei** [comment]
Thankyou so much. Really helpful. This work helps implement actual user scenarios with services that have restrictions regarding unique parameters being passed.

**Comment by bojand** [comment]
Hello, thanks for answering these question @ezsilmar ! Closing this issue now that the PR is merged. Please feel free to open new issues if there are problems with the new feature.

**Comment by pavanapriya** [comment]
Hey! I need help with a scenario where my server takes a struct as input. Say a string as 1 parameter, array of string as another input. May be a college server with name of student, array of subjects. Could you please give an example of ghz -d for this scenario.

Also,can ghz tool be used if I have a scenario where my server throws error if the input has same name of student. So ideally I want to test my server with different inputs and check how many requests it can process in single time. Kind of like multithreading.
